import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
// import styles from "../styles/Home.module.scss";
import styles from "../styles/Header.module.scss";
import HeaderBG from "../images/headerImg2.png";
import News from "../components/News";
import MenuDesktop from "../components/MenuDesktop";
import { useEffect, useState } from "react";
import MenuMobile from "../components/MenuMobile";
import Order from "../components/Order";
import Partners from "../components/Partners";
import Footer from "../components/Footer";
import Menu from "../components/MenuDesktop";

export default function Home() {
  const [width, setWidth] = useState(null);
  const updateWidthAndHeight = () => {
    setWidth(window.innerWidth);
  };
  useEffect(() => {
    window.addEventListener("resize", updateWidthAndHeight);
    return () => window.removeEventListener("resize", updateWidthAndHeight);
  });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Playfair+Display:wght@700&display=swap"
          rel="stylesheet"
        /> */}
      </Head>
      <Navbar />
      <Header />
      <News />
      <section id="table_of_contents">
        <MenuDesktop />
        <MenuMobile />
      </section>
      {/* {width > 990 ? <MenuDesktop /> : <MenuMobile />} */}

      <Order />
      <Partners />
      <Footer />
    </div>
  );
}
